// spring-ai-alibaba-examples/playground-flight-booking/frontend/src/views/home/Message.vue
<script setup lang="ts">
import type { MessageItem } from "@/types/message";
import Markdown from "vue3-markdown-it";
let message = defineProps<MessageItem>();
</script>

<template>
  <div>
    <a-comment>
      <template #author
        ><a style="font-size: 16px">{{
          message.role === "user" ? "🧑‍💻 You" : "🤖 Assistant"
        }}</a></template
      >
      <template #content>
        <div
          style="
            width: 98%;
            border-radius: 5px;
            padding: 20px;
            background: white;
          "
        >
          <markdown :source="message.content"></markdown>
          <!--          <p>-->
          <!--            {{ message.content }}-->
          <!--          </p>-->
        </div>
      </template>
    </a-comment>
  </div>
</template>

<style scoped lang="less"></style>

// spring-ai-alibaba-examples/playground-flight-booking/frontend/components/Message.tsx
import Markdown from "react-markdown";

export interface MessageItem {
  role: 'user' | 'assistant';
  content: string;
}

interface MessageProps {
  message: MessageItem;
}

export default function Message({message}: MessageProps) {
  return (
    <div className="mb-l">
      <div className="font-bold">{message.role === 'user' ? '🧑‍💻 You' : '🤖 Assistant'}</div>
      <div>
        <Markdown>
          {message.content}
        </Markdown>
      </div>
    </div>
  )
};
